#!/bin/bash

# ECOSYSTEMAWS Critical Auth Fix Commit Script - With Linting Fixes
# Generated by Lead Architect Agent

echo "========================================="
echo "ECOSYSTEMAWS - Critical Auth Fix Commit"
echo "   WITH FULL TYPESCRIPT COMPLIANCE"
echo "========================================="
echo ""

# Navigate to project directory
cd /Users/ryleebenson/Desktop/ECOSYSTEMAWS

# Show current status
echo "📋 Current Git Status:"
git status
echo ""

# Run linter to verify all issues are fixed
echo "🔍 Running ESLint to verify fixes..."
npx eslint lib/amplify-server-utils.ts middleware.ts app/api/stripe/connect/route.ts
echo ""

# Stage the critical files
echo "📦 Staging modified files..."
git add lib/amplify-server-utils.ts
git add middleware.ts
git add app/api/stripe/connect/route.ts
echo "✅ Files staged"
echo ""

# Commit with comprehensive message
echo "💾 Committing changes..."
git commit -m "fix(auth): implement unified server-side auth context with full TypeScript compliance

- Establishes a single source of truth for server-side Amplify operations in /lib/amplify-server-utils.ts
- Refactors middleware and API routes to use the new getAuthenticatedUser helper
- Corrects middleware redirect paths and expands the list of protected routes
- Adds comprehensive TypeScript interfaces eliminating all 'any' types
- Implements explicit return types on all functions
- Reduces complexity by extracting action handler logic
- Ensures full ESLint compliance with strict TypeScript rules
- This change resolves a critical build/runtime failure and unblocks the deployment pipeline"

echo ""
echo "✅ Commit complete!"
echo ""

# Verify the commit
echo "🔍 Verification - Latest commit:"
git log --oneline -1
echo ""

echo "========================================="
echo "Ready to push? Run: git push origin main"
echo "========================================="